### ISSUE TITLE
Rapportmappning - Något gick fel...

### ISSUE THREAD

**Issue by idaber** [victor--/viss-bugs#236]
![image](https://cloud.githubusercontent.com/assets/11041042/13460815/bec7d19e-e07d-11e5-955a-54aa4b598200.png)
http://develop.vattenmyndigheten.local/WFD2016v601.Mappings/

**Comment by idaber** [comment]
Invalid object name 'WFD2016v601Mappings.SurfaceWaterBody_SWPrioritySubstance_PS_Enum_flipped'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at WFD2016.XSDClasses.Mappings.DBCommand.ExecuteReader() in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XSDClasses\Mappings\DBCommand.cs:line 1106
   at WFD2016.XSDClasses.Mappings.DBCommand.Read() in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XSDClasses\Mappings\DBCommand.cs:line 431
   at WFD2016.XSDClasses.Mappings.ParameterToXSDEnumMapping.Load(MappingAttribute attribute) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XSDClasses\Mappings\ParameterToXSDEnumMapping.cs:line 23
   at WFD2016.XSDClasses.Mappings.MappingFactory.LoadMapping(MappingAttribute attribute) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XSDClasses\Mappings\MappingFactory.cs:line 310
   at WFD2016.XMLGenerator.GeneratorBase`1.GetMapping[MapperType](Type baseItem, String propertyName) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XMLGenerator\GeneratorBase.cs:line 62
   at WFD2016.XMLGenerator.SWBGenerator.get_SWPrioritySubstanceMappings() in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XMLGenerator\SWBGenerator.cs:line 245
   at WFD2016.XMLGenerator.SWBGenerator.GetSWPrioritySubstance(Water water) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XMLGenerator\SWBGenerator.cs:line 613
   at WFD2016.XMLGenerator.SWBGenerator.GetSurfaceWaterBody(SearchConditions sc) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XMLGenerator\SWBGenerator.cs:line 447
   at WFD2016.XMLGenerator.SWBGenerator.Generate(String areaEUID) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XMLGenerator\SWBGenerator.cs:line 326
   at WFD2016.XMLGenerator.Generator.GenerateSWB(String areaEUID) in c:\VSS\TFS\Vattenmyndigheten - VISS\WFD2016.XMLGenerator\Generator.cs:line 75
   at WFD2016.WebInterface.WFD2016XMLGeneratorScheduledJob.Execute() in c:\VSS\TFS\Vattenmyndigheten - VISS\www\WFD2016XMLGeneratorScheduledJob.cs:line 199
   at WaterCharacteristics.Classes.Data.ScheduledJobWrapper.RunJob(Boolean force) in c:\VSS\TFS\Vattenmyndigheten - VISS\www\Classes\Data\ScheduledJobWrapper.cs:line 400
Schemaläggning
Inaktivera tjänsten	
Cykel	 varje    Bygg uttryck
Starttid	 :  
Använd eget cron-uttryck 	
0 0 0/1 * * ?
Testa cron-uttryck	
Ändringskommentar
Uppdaterad:	2016-03-02 13:55	 	 
Uppdaterad av:	ida@meridium.se		 
Spara  Kör nu!  Visa logg

**Comment by victor--** [comment]
Fixat!
